#!/usr/bin/env python3
import argparse
import wave
from pathlib import Path


def read_mono16(path):
    with wave.open(str(path), "rb") as wav:
        if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
            raise ValueError(f"{path}: expected 16-bit mono PCM")
        if wav.getframerate() not in (10937, 11025):
            raise ValueError(f"{path}: expected ~11 kHz sample rate")
        frames = wav.readframes(wav.getnframes())
    return [int.from_bytes(frames[i:i + 2], "little", signed=True) for i in range(0, len(frames), 2)]


def trim_silence(samples, threshold):
    start = 0
    end = len(samples)
    while start < end and abs(samples[start]) <= threshold:
        start += 1
    while end > start and abs(samples[end - 1]) <= threshold:
        end -= 1
    return samples[start:end]


def to_u8(samples):
    out = bytearray()
    for sample in samples:
        value = (sample + 32768) >> 8
        out.append(max(0, min(255, value)))
    return bytes(out)


def main():
    parser = argparse.ArgumentParser(description="Trim WAV silence and convert SFX to unsigned 8-bit raw.")
    parser.add_argument("--out-dir", default="assets/resources")
    parser.add_argument("--asm", default="assets/resources/sfx_len.asm")
    parser.add_argument("--threshold", type=int, default=384)
    parser.add_argument("wav", nargs="+")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = ["        ; Generated by tools/wav2sfx.py"]

    for wav_path in args.wav:
        source = Path(wav_path)
        samples = trim_silence(read_mono16(source), args.threshold)
        raw = to_u8(samples)
        name = source.stem.upper()
        out_path = out_dir / f"{source.stem}.raw"
        out_path.write_bytes(raw)
        lines.append(f"SFX_{name}_LEN equ {len(raw)}")

    Path(args.asm).write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
