EmmWin.P0	EQU	#82
EmmWin.P1	EQU	#A2
EmmWin.P2	EQU	#C2
EmmWin.P3	EQU	#E2
Y_PORT          EQU     #89
RGADR           EQU     Y_PORT
RGMOD           EQU     #C9
SIO_CONTROL_A   EQU     #19
SIO_DATA_REG_A  EQU     #18
CTC_CH0         EQU     #10
CTC_CH1         EQU     #11
CTC_CH2         EQU     #12
CTC_CH3         EQU     #13

CACHE_ON_PORT   EQU     #FB
CACHE_OFF_PORT  EQU     #7B
SYS_PORT_OFF    EQU     #3C
SYS_MAP_CACHE   EQU     #04
SYS_MAP_DSS     EQU     #03
ISA_SYSTEM_PORT EQU     #1FFD
ISA_SYSTEM_DSS  EQU     #01

CACHE_RENDER_BASE EQU   #0100

CBL_CTRL        EQU     #004E
CBL_DATA        EQU     #004F
CBL_CTRL_OFF    EQU     #00
CBL_CTRL_RUN_11K_MONO EQU #88           ; 7.8125 kHz mono (CBL rate code #8)
CBL_CTRL_RUN_11K_MONO_INT EQU #98       ; 7.8125 kHz mono + INT
CBL_SILENCE     EQU     #80
SFX_CBL_CHUNK_BYTES EQU 128
