EmmWin.P0	EQU	#82
EmmWin.P1	EQU	#A2
EmmWin.P2	EQU	#C2
EmmWin.P3	EQU	#E2
Y_PORT          EQU     #89
RGADR           EQU     Y_PORT
RGMOD           EQU     #C9
SIO_CONTROL_A   EQU     #19
SIO_DATA_REG_A  EQU     #18
CTC_CH0         EQU     #10
CTC_CH1         EQU     #11
CTC_CH2         EQU     #12
CTC_CH3         EQU     #13
